@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Aug 30 14:56:56 +0700 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim Matched_Filter_wrapper_behav -key {Behavioral:sim_1:Functional:Matched_Filter_wrapper} -tclbatch Matched_Filter_wrapper.tcl -protoinst "protoinst_files/Matched_Filter.protoinst" -view C:/Vivado_Projects/Matched_Filter/MatchedFilter-Vivado/MatchedFilter-Vivado.srcs/sim_1/imports/MatchedFilter-Vivado/design_1_wrapper_behav.wcfg -view C:/Vivado_Projects/Matched_Filter/MatchedFilter-Vivado/design_2_wrapper_behav.wcfg -log simulate.log"
call xsim  Matched_Filter_wrapper_behav -key {Behavioral:sim_1:Functional:Matched_Filter_wrapper} -tclbatch Matched_Filter_wrapper.tcl -protoinst "protoinst_files/Matched_Filter.protoinst" -view C:/Vivado_Projects/Matched_Filter/MatchedFilter-Vivado/MatchedFilter-Vivado.srcs/sim_1/imports/MatchedFilter-Vivado/design_1_wrapper_behav.wcfg -view C:/Vivado_Projects/Matched_Filter/MatchedFilter-Vivado/design_2_wrapper_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
